In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import numba


In [2]:
def generate_the_laplace_matrix_with_size(N=3):
    """
    assume sqrt(N) is an integer. Generate the Laplace matrix with size N

    """
    nsq = N * N
    A   = np.zeros((nsq, nsq))
    
    for i in range(nsq):
        for j in range(nsq):
            if i == j:
                A[i, j] = 4
            elif (i == j + N or i == j - N):
                A[i, j] = -1
            elif (i == j + 1 or i == j - 1):
                if (((i + 1) % N == 0 and (j % N == 0)) or ((i % N == 0 and ((j + 1) % N == 0)))) and i != 0 and j != 0:
                    A[i, j] = 0
                else:
                    A[i, j] = -1
            else:
                A[i, j] = 0


    return A

In [3]:
N = 3
A = generate_the_laplace_matrix_with_size(N)
print(A)

[[ 4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  4.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  4.]]


In [4]:
def generate_the_rhs_vector_with_size(N=3):
    """
    Assume sqrt(N) is an integer. Generate the right-hand side vector with size N
    """
    b = np.zeros(N * N)
    #TODO
    for i in range(N * N):
        if i == 4:
            b[i] = 1
        else:
            b[i] = 0
    
    return b

In [5]:
b = generate_the_rhs_vector_with_size(N=N)
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
from scipy import linalg

x = linalg.solve(A, b)

In [7]:
def convert_solution(x):
    usize = np.sqrt(len(x))
    # print(usize)
    u = x.reshape(int(usize),int(usize)).transpose()
    return u

In [8]:
u = convert_solution(x)
print(u)

[[0.0625 0.125  0.0625]
 [0.125  0.375  0.125 ]
 [0.0625 0.125  0.0625]]
